### ISSUE TITLE
Colorscheme?

### ISSUE THREAD

**Issue by AAlakkad** [jonathanglasmeyer/dotfiles#1]
Hey!

Can you mention the colorscheme you're using in the README? didn't find it in the vim files. maybe it's a terminal colorscheme?

**Comment by jonathanewerner** [comment]
Sorry, colorscheme i am using in the Readme? I don't get it. :)

**Comment by AAlakkad** [comment]
I meant the colorscheme name, if you can mention it in the readme :)

**Comment by jonathanewerner** [comment]
i basically use gruvbox but then not really because i also use [semantic-highlight](https://github.com/jaxbot/semantic-highlight.vim) plus some other customizations on top. :)

**Comment by AAlakkad** [comment]
Nice!
Already using Gruvbox, I felt that there's something different in your colors :)

**Comment by jonathanewerner** [comment]
If you really wanna go down the rabbit hole you could check out https://github.com/jonathanewerner/semantic-highlight-base-colorscheme  

It's basically gruvbox optimized for the semantic highlight thing.

**Comment by AAlakkad** [comment]
Can I ask again? :)
The colorscheme for the terminal, I assume it's gruvbox? did you copy-paste the colors one by one?

**Comment by jonathanewerner** [comment]
:) sure. 
Yea I think so. 

https://github.com/jonathanewerner/dotfiles/blob/master/config/roxterm.sourceforge.net/Colours/Default

I use roxterm nowadays. Each term has its own config.. Annoying.
